In [10]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

In [11]:
df = pd.read_csv(r"datasets\csv_file.csv")

In [12]:
df.head(3)

,id,title,overview,cast,crew,keywords,genres
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",TomHanks TimAllen DonRickles,JohnLasseter,jealousy toy boy friendship friends rivalry bo...,Animation Comedy Family
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,RobinWilliams JonathanHyde KirstenDunst,JoeJohnston,boardgame disappearance basedonchildren'sbook ...,Adventure Fantasy Family
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,WalterMatthau JackLemmon Ann-Margret,HowardDeutch,fishing bestfriend duringcreditsstinger oldmen,Romance Comedy

In [13]:
df=df.head(5000)

In [14]:
df.isnull().sum()

id            0
title         0
overview      0
cast         76
crew         28
keywords    637
genres      101
dtype: int64

In [15]:
df.dropna(inplace=True)

In [16]:
df.duplicated().sum()

2

In [17]:
df.drop_duplicates(keep=False, inplace=True)

In [18]:
df.duplicated().sum()

0

In [19]:
df.shape

(4322, 7)

In [20]:
df['tags'] = df['keywords'] + df['genres'] + df['cast'] + df['crew']

In [21]:
df = df.drop(['cast', 'crew', 'keywords', 'genres'], axis=1)

In [22]:
df.head(3)

,id,title,overview,tags
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",jealousy toy boy friendship friends rivalry bo...
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,boardgame disappearance basedonchildren'sbook ...
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,fishing bestfriend duringcreditsstinger oldmen...

In [23]:
# id = tmbdid

In [24]:
df['overview'] = df['overview'].apply(lambda x:x.split())

In [25]:
df['overview'] = df['overview'].apply(lambda x:" ".join(x))

In [26]:
df.head(3)

,id,title,overview,tags
0,862,Toy Story,"Led by Woody, Andy's toys live happily in his ...",jealousy toy boy friendship friends rivalry bo...
1,8844,Jumanji,When siblings Judy and Peter discover an encha...,boardgame disappearance basedonchildren'sbook ...
2,15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,fishing bestfriend duringcreditsstinger oldmen...

In [27]:
df['tags'] = df['tags'] + df['overview']

In [28]:
df = df.drop(['overview'], axis=1)

In [29]:
df['tags'] = df['tags'].apply(lambda x:x.lower())

In [30]:
df

,id,title,tags
0,862,Toy Story,jealousy toy boy friendship friends rivalry bo...
1,8844,Jumanji,boardgame disappearance basedonchildren'sbook ...
2,15602,Grumpier Old Men,fishing bestfriend duringcreditsstinger oldmen...
3,31357,Waiting to Exhale,basedonnovel interracialrelationship singlemot...
4,11862,Father of the Bride Part II,baby midlifecrisis confidence aging daughter m...
...,...,...,...
4993,108267,The Lone Ranger and the Lost City of Gold,lonerangeraction adventure westernclaytonmoore...
4995,15999,Vampire Hunter D: Bloodlust,bountyhunter katana future vampire halfvampire...
4996,614,Wild Strawberries,adultery identity dream journeyinthepast profe...
4998,121703,Cattle Queen of Montana,montana nativeamerican cattleranch landgrabwes...
4999,77955,Under the Skin,womandirectordramasamanthamorton clairerushbro...

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
countvectorizer = CountVectorizer(stop_words='english', max_features=5000)

In [32]:
vectors = countvectorizer.fit_transform(df['tags']).toarray()
# toarray() because default result will be in a sparse matrix form

In [33]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
countvectorizer.get_feature_names()

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '1920s',
 '1930',
 '1930s',
 '1934',
 '1940s',
 '1944',
 '1950s',
 '1955',
 '1957',
 '1959',
 '1960',
 '1960s',
 '1965',
 '1970',
 '1970s',
 '1980',
 '1980s',
 '1986',
 '1990',
 '1990s',
 '1992',
 '1994',
 '1996',
 '1999',
 '19th',
 '20',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '40',
 '50',
 '50s',
 '60',
 '60s',
 '70',
 '80',
 '90s',
 'abandoned',
 'abducted',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abroad',
 'abruptly',
 'absence',
 'abuse',
 'abused',
 'abusive',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accidents',
 'acclaimed',
 'accompanied',
 'account',
 'accountant',
 'accused',
 'ace',
 'acid',
 'acquired',
 'act',
 'acting',
 'action',
 'actions',
 'activist',
 'activities',
 'actor',
 'actorcomedy',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'ad',
 'ada',
 'adam',
 'adams',
 'adaptation',
 'add',
 'addict',
 'addicted',
 'addiction',
 'addition',
 'adolescence',
 'adolescent',
 'adopted',
 'adoption',
 'adopts',
 'adorable',
 'adult',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventurer',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affect',
 'affected',
 'affection',
 'affections',
 'affluent',
 'afghan',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'aftercreditsstingeradventure',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressionbyanimal',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airforce',
 'airline',
 'airplane',
 'airplanecrash',
 'airport',
 'al',
 'alan',
 'alaska',
 'albert',
 'album',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alex',
 'alice',
 'alicia',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alive',
 'allegory',
 'allen',
 'alliance',
 'allied',
 'allies',
 'alligator',
 'allow',
 'allowed',
 'allowing',
 'allows',
 'alongside',
 'alpacino',
 'alps',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amateur',
 'amazing',
 'amazon',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americandream',
 'americanfootball',
 'americans',
 'amnesia',
 'amp',
 'amusement',
 'amusementpark',
 'amy',
 'ananka',
 'ancient',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelo',
 'angels',
 'anger',
 'angry',
 'angus',
 'animal',
 'animalhorrorhorror',
 'animals',
 'animated',
 'animation',
 'ann',
 'anna',
 'anne',
 'annebancroft',
 'anneheche',
 'annie',
 'anniversary',
 'announces',
 'annual',
 'anonymity',
 'answer',
 'answers',
 'ant',
 'anthology',
 'anthony',
 'anthonyhopkins',
 'anthropologist',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antisemitism',
 'antoine',
 'anton',
 'antoniobanderas',
 'anymore',
 'apache',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apollo',
 'appear',
 'appearance',
 'appearing',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approached',
 'approaches',
 'arab',
 'archaeologist',
 'archeology',
 'archie',
 'architect',
 'arctic',
 'area',
 'aren',
 'argentina',
 'aristocrat',
 'aristocratic',
 'arizona',
 'arkansas',
 'arm',
 'armed',
 'arms',
 'armstrong',
 'army',
 'arrange',
 'arranged',
 'arrangedmarriage',
 'arranges',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrived',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'artists',
 'arts',
 'ash',
 'ashes',
 'asian',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspires',
 'aspiring',
 'assassin',
 'assassination',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'asylum',
 'atlantic',
 'atmosphere',
 'atomic',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attemptedmurder',
 'attempting',
 'attempts',
 'attempttoescape',
 'attend',
 'attendant',
 'attending',
 'attention',
 'attic',
 'attitude',
 'attorney',
 'attract',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audition',
 'august',
 'aunt',
 'aurora',
 'austin',
 'australia',
 'australian',
 'austria',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'autobiographical',
 'automobile',
 'avenge',
 'avenger',
 'avenging',
 'average',
 'aviation',
 'avoid',
 'award',
 'awards',
 'aware',
 'away',
 'awry',
 'axel',
 'babe',
 'baby',
 'babysitter',
 'bachelor',
 'backdrop',
 'background',
 'backgrounds',
 'bad',
 'badly',
 'bag',
 'bail',
 'baker',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandit',
 'bandits',
 'bangkok',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'banks',
 'bar',
 'barbara',
 'barely',
 'barn',
 'baron',
 'barry',
 'bars',
 'bartender',
 'base',
 'baseball',
 'based',
 'basedoncomic',
 'basedonnovel',
 'basedonplayormusical',
 'basedonshortstory',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basement',
 'basketball',
 'bat',
 'bates',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'beachhouse',
 'bear',
 'bearing',
 'bears',
 'beast',
 'beat',
 'beaten',
 'beating',
 'beatrice',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'believe',
 'believed',
 'believes',
 'bell',
 'belongs',
 'beloved',
 'ben',
 'benefactor',
 'benjamin',
 'benny',
 'benson',
 'bent',
 'berlin',
 'bernard',
 'bernie',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'better',
 'betty',
 'beverly',
 'beverlyd',
 'beverlyhills',
 'bianca',
 'bibiane',
 'bible',
 'bickering',
 'bicycle',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billionaire',
 'billy',
 'billybobthornton',
 'billycrystal',
 'biographical',
 'biography',
 'biopic',
 'bird',
 'birds',
 'birth',
 'birthday',
 'bisexuality',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackandwhite',
 'blackhumor',
 'blackmail',
 'blackpeople',
 'blade',
 'blake',
 'blame',
 'blaxploitation',
 'blind',
 'blindnessandimpairedvision',
 'blob',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'blues',
 'bmovie',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bodies',
 'body',
 'bodyguard',
 'bomb',
 'bomber',
 'bombing',
 'bond',
 'bone',
 'bones',
 'book',
 'books',
 'booze',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'bounty',
 'bountyhunter',
 'bowden',
 'bowles',
 'box',
 'boxer',
 'boxing',
 'boxingmatch',
 'boy',
 'boyfriend',
 'boys',
 'brad',
 'brain',
 'brash',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'brenda',
 'brian',
 'bride',
 'bridge',
 'bridgetfonda',
 'brief',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'britain',
 'british',
 'britisharmy',
 'britishsecretservice',
 'broadcast',
 'broadway',
 'broken',
 'broker',
 'bronx',
 'brooklyn',
 'brooks',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewillis',
 'bruno',
 'brutal',
 'brutality',
 'brutally',
 'buck',
 'buddies',
 'buddy',
 'buddycop',
 'budget',
 'build',
 'building',
 'builds',
 'built',
 'bullies',
 'bully',
 'bum',
 'bumbling',
 'bunch',
 'burglar',
 'burglary',
 'buried',
 'buriedalive',
 'burns',
 'burton',
 'bury',
 'bus',
 'business',
 'businessman',
 'bust',
 'busy',
 'butcher',
 'butler',
 'buy',
 'buys',
 'buzz',
 'cab',
 'cabaret',
 'cabin',
 'caesar',
 'cage',
 'caine',
 'cairo',
 'california',
 'callahan',
 'called',
 'calls',
 'calm',
 'calvin',
 'came',
 'camelot',
 'camera',
 'cameron',
 'camerondiaz',
 'camille',
 'camp',
 'campaign',
 'campbell',
 'camps',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cane',
 'cannibal',
 'cannon',
 'cannonball',
 'capable',
 'capone',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'careers',
 'carefree',
 'cares',
 'caretaker',
 'caribbean',
 'carl',
 'carlos',
 'carmen',
 'carnival',
 'carol',
 'carpenter',
 'carrace',
 'carries',
 'carry',
 'carrying',
 'cars',
 'carter',
 'cartoon',
 'case',
 'cases',
 'casey',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catch',
 'catches',
 'catching',
 'cathedral',
 'catherine',
 'catholic',
 'cats',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'celebrate',
 'celebration',
 'celebrity',
 'cell',
 'cellar',
 'cellist',
 'cemetery',
 'cenobites',
 'center',
 'centered',
 'centers',
 'central',
 'centralandsouthamerica',
 'century',
 'ceremony',
 'certain',
 'chain',
 'chainsaw',
 'chair',
 'challenge',
 'challenged',
 'challenges',
 'champ',
 'champion',
 'championship',
 'chan',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'chaos',
 'chaotic',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charless',
 'charley',
 'charlie',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'charms',
 'chase',
 'chased',
 'chases',
 'chauffeur',
 'cheap',
 'cheating',
 'cheech',
 'cheerleader',
 'chef',
 'chemical',
 'chemistry',
 'chess',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhood',
 'childhoodmemory',
 'childprodigy',
 'children',
 'chilling',
 'chimpanzee',
 'china',
 'chinatown',
 'chinese',
 'chip',
 'chocolate',
 'choice',
 'choices',
 'chong',
 'choose',
 'chooses',
 'chosen',
 'chris',
 'christ',
 'christian',
 'christianity',
 'christina',
 'christine',
 'christmas',
 'christmasparty',
 'christmastree',
 'christopher',
 'christopherlloyd',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'cigar',
 'cigarettesmoking',
 'cinema',
 'circle',
 'circumstances',
 'circus',
 'cities',
 'citizen',
 'citizens',
 'city',
 'civil',
 'civilian',
 'civilization',
 'civilwar',
 'clad',
 'claim',
 'claiming',
 'claims',
 'claire',
 'clan',
 'clara',
 'clark',
 'clash',
 'class',
 'classdifferences',
 'classic',
 'classichorror',
 'classicnoir',
 'classmate',
 'classmates',
 'claudevandamme',
 'claus',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climax',
 'climbing',
 'clique',
 'clock',
 'clone',
 'cloning',
 'close',
 'closed',
 'closer',
 'clothes',
 'clown',
 'club',
 'clubs',
 'clueless',
 'clues',
 'clutches',
 'coach',
 'coal',
 'coast',
 'coastal',
 'cocaine',
 'cocky',
 'code',
 'cody',
 'coffee',
 'coffin',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collision',
 'colonel',
 'colony',
 'colorado',
 'coma',
 'combat',
 'come',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comic',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commanding',
 'commando',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'committing',
 'common',
 'communist',
 'community',
 'companion',
 'company',
 'compete',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'conan',
 'concentration',
 'concentrationcamp',
 'concerns',
 'concert',
 'condition',
 'conditions',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'conflicts',
 'confront',
 'confrontation',
 'confronted',
 'confronts',
 'confused',
 'confusion',
 'conman',
 'connect',
 'connected',
 'connection',
 'connie',
 'connor',
 'conquer',
 'cons',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'conspire',
 'constant',
 'constantly',
 'construction',
 'contact',
 'containing',
 'contains',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'contracts',
 'control',
 ...]

In [35]:
import nltk
from nltk.stem.porter import PorterStemmer
port = PorterStemmer()

In [36]:
def stem(text):
    y = []
    for i in text.split():
        y.append(port.stem(i))
    return " ".join(y)

In [37]:
df['tags'] = df['tags'].apply(stem)

In [38]:
df

,id,title,tags
0,862,Toy Story,jealousi toy boy friendship friend rivalri boy...
1,8844,Jumanji,boardgam disappear basedonchildren'sbook newho...
2,15602,Grumpier Old Men,fish bestfriend duringcreditssting oldmenrom c...
3,31357,Waiting to Exhale,basedonnovel interracialrelationship singlemot...
4,11862,Father of the Bride Part II,babi midlifecrisi confid age daughter motherda...
...,...,...,...
4993,108267,The Lone Ranger and the Lost City of Gold,lonerangeract adventur westernclaytonmoor jays...
4995,15999,Vampire Hunter D: Bloodlust,bountyhunt katana futur vampir halfvampir adul...
4996,614,Wild Strawberries,adulteri ident dream journeyinthepast professo...
4998,121703,Cattle Queen of Montana,montana nativeamerican cattleranch landgrabwes...
4999,77955,Under the Skin,womandirectordramasamanthamorton clairerushbro...

In [39]:
df['tags'][0]

"jealousi toy boy friendship friend rivalri boynextdoor newtoy toycomestolifeanim comedi familytomhank timallen donricklesjohnlasseterl by woody, andy' toy live happili in hi room until andy' birthday bring buzz lightyear onto the scene. afraid of lose hi place in andy' heart, woodi plot against buzz. but when circumst separ buzz and woodi from their owner, the duo eventu learn to put asid their differences."

In [40]:
#in this problem, we cslculate cosine distance, not eucledian distance
#in higher dimensions, eucledian distance is not that accurate

In [41]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
sim = TfidfVectorizer(stop_words='english')

In [42]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [43]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [44]:
cosine_similarity(vectors)

array([[1.        , 0.02094729, 0.        , ..., 0.        , 0.        ,
        0.04643635],
       [0.02094729, 1.        , 0.0547791 , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.0547791 , 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.03380617],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.04643635, 0.        , 0.        , ..., 0.03380617, 0.        ,
        1.        ]])

In [45]:
cosine_similarity(vectors).shape

(4322, 4322)

In [46]:
similarity = cosine_similarity(vectors)

In [47]:
def recommend(movie):
    movie_index = df[df['title']==movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(df.iloc[i[0]].title)

In [48]:
recommend('Jumanji')

Dungeons & Dragons
eXistenZ
Sudden Death
Any Given Sunday
D3: The Mighty Ducks

In [49]:
recommend('Batman Begins')

IndexError: index 0 is out of bounds for axis 0 with size 0

In [50]:
import pickle

In [51]:
df=df.head(5000)
pickle.dump(df.to_dict(),open('movies_content_dict.pkl','wb'))

In [52]:
pickle.dump(similarity,open('similarity_content.pkl','wb'))

In [53]:
import bz2

In [55]:
def compressed_pickle(title, data):
    with bz2.BZ2File(title + '.pbz2', 'w') as f: 
        pickle.dump(data, f)
compressed_pickle('similarity_content', similarity)